"""Hybrid-graphics (NVIDIA Optimus) mode switching — Wayland only.

Locks the machine to the integrated GPU, or restores hybrid (on-demand NVIDIA),
by blacklisting the NVIDIA/nouveau kernel modules and powering the dGPU off via
udev. This is the same mechanism EnvyControl uses, pared down to the two modes
that make sense on a Wayland compositor:

  * ``integrated`` — blacklist every NVIDIA/nouveau module and remove the dGPU
    PCI devices on boot, so nothing can ever bring the card up (it parks in
    D3cold, ~0 W). No app can offload to it.
  * ``hybrid`` — remove those files so the NVIDIA driver loads normally again and
    apps can render on it on demand (``prime-run`` / ``__NV_PRIME_RENDER_OFFLOAD``).

There is deliberately no X11 ``nvidia`` mode: it needs xorg.conf + display-manager
xrandr glue that is meaningless under Wayland.

Reads (``nvidia_present``/``current_mode``) are unprivileged sysfs/file checks.
``set_mode`` writes under /etc and rebuilds the initramfs, so it must run as root
(through the Vantage helper). A reboot is required for any change to take effect.
"""
import glob
import logging
import os
import shutil
import subprocess
import sys

log = logging.getLogger("vantage.gpu")

MODES = ("integrated", "hybrid")

BLACKLIST_PATH = "/etc/modprobe.d/vantage-blacklist-nvidia.conf"
UDEV_INTEGRATED_PATH = "/etc/udev/rules.d/50-vantage-remove-nvidia.rules"

# Persistent proof that this host has an NVIDIA dGPU. In integrated mode the udev
# rule removes the card from the PCI bus, so a live scan can no longer see it —
# and once reverted to hybrid (before the reboot) the blacklist files are gone
# too, leaving nothing to detect. We stamp this marker on the first mode switch
# and never delete it, so the control stays available through every transition.
MARKER_PATH = "/var/lib/vantage/has-nvidia-dgpu"

# Files this module owns; removing them reverts to hybrid (distro default).
_OWNED_FILES = (BLACKLIST_PATH, UDEV_INTEGRATED_PATH)

BLACKLIST_CONTENT = """# Automatically generated by Vantage — integrated graphics mode

blacklist nouveau
blacklist nova_core
blacklist nova_drm
blacklist nvidia
blacklist nvidia_drm
blacklist nvidia_uvm
blacklist nvidia_modeset
blacklist i2c_nvidia_gpu
alias nouveau off
alias nova_core off
alias nova_drm off
alias nvidia off
alias nvidia_drm off
alias nvidia_uvm off
alias nvidia_modeset off
alias i2c_nvidia_gpu off
"""

UDEV_INTEGRATED_CONTENT = """# Automatically generated by Vantage — integrated graphics mode

# Remove NVIDIA USB xHCI Host Controller devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{power/control}="auto", ATTR{remove}="1"

# Remove NVIDIA USB Type-C UCSI devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{power/control}="auto", ATTR{remove}="1"

# Remove NVIDIA Audio devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{power/control}="auto", ATTR{remove}="1"

# Remove NVIDIA VGA/3D controller devices
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x03[0-9]*", ATTR{power/control}="auto", ATTR{remove}="1"
"""

NVIDIA_VENDOR = "0x10de"


def nvidia_present():
    """True if an NVIDIA VGA/3D-controller PCI device exists on this machine.

    Pure sysfs scan — never touches lspci and never wakes the card. Used to
    auto-hide the control on machines without an NVIDIA dGPU.
    """
    for dev in glob.glob("/sys/bus/pci/devices/*"):
        try:
            with open(os.path.join(dev, "vendor")) as fh:
                vendor = fh.read().strip()
            with open(os.path.join(dev, "class")) as fh:
                cls = fh.read().strip()
        except OSError:
            continue
        # class 0x030000 = VGA, 0x030200 = 3D controller.
        if vendor == NVIDIA_VENDOR and (cls.startswith("0x0300")
                                        or cls.startswith("0x0302")):
            return True
    return False


def current_mode():
    """Return 'integrated' if our blacklist+udev files are in place, else 'hybrid'."""
    if os.path.exists(BLACKLIST_PATH) and os.path.exists(UDEV_INTEGRATED_PATH):
        return "integrated"
    return "hybrid"


def applied_mode():
    """Return the mode currently *in effect* (as booted), vs current_mode()'s
    on-disk configuration.

    Writing/removing the blacklist files changes current_mode() instantly, but
    the live GPU state only changes on reboot. The running state is read straight
    from the bus: in hybrid the NVIDIA PCI device is present; in integrated the
    boot-time udev rule has removed it. So a present device means we booted
    hybrid, its absence means we booted integrated. Comparing applied_mode() with
    current_mode() tells the UI whether a reboot is still pending.
    """
    return "hybrid" if nvidia_present() else "integrated"


def available():
    """True if the graphics-mode control should be offered on this machine.

    A live PCI scan finds the dGPU in hybrid mode — but in integrated mode our
    udev rule has *removed* the NVIDIA device from the bus, so nvidia_present()
    would report False and the control would vanish, stranding the user with no
    way back. The persistent marker (stamped on the first switch) keeps the
    toggle visible across every transition, including the revert-before-reboot
    window where neither the device nor the blacklist files are present.
    """
    return (nvidia_present() or current_mode() == "integrated"
            or os.path.exists(MARKER_PATH))


def _write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    log.info("wrote %s", path)


def _remove_owned():
    for path in _OWNED_FILES:
        try:
            os.remove(path)
            log.info("removed %s", path)
        except FileNotFoundError:
            pass


def _persistenced(action):
    """Best-effort enable/disable of nvidia-persistenced (ignored if absent)."""
    try:
        subprocess.run(["systemctl", action, "nvidia-persistenced.service"],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                       check=False)
    except OSError:
        pass


def _initramfs_candidates():
    """Return an ordered list of argvs that can regenerate the initramfs.

    Distro-agnostic by design: rather than trusting a single ``/etc/*-release``
    guess, we collect every regeneration command whose tool is actually present
    and applicable, most-specific first, and the caller tries them in order until
    one succeeds. This covers the common Optimus-laptop distros and their
    initramfs generators:

      * rpm-ostree   — Fedora Silverblue / atomic (image-based)
      * update-initramfs — Debian / Ubuntu / Pop!_OS / Mint
      * limine-mkinitcpio — CachyOS & others using the Limine mkinitcpio hook
                            (no /etc/mkinitcpio.d presets; rebuilds all kernels)
      * mkinitcpio -P — Arch / Manjaro / EndeavourOS (only when presets exist)
      * dracut       — Fedora / RHEL / openSUSE, and Arch-with-dracut setups
      * booster      — Arch alternative generator
      * kernel-install / reinstall-kernels — systemd UKI-based setups

    Trying in order is safe because the entries are alternative invocations that
    each write to their own configured output; the first one that belongs to the
    system succeeds, and we stop there.
    """
    cands = []

    # Image-based / atomic first — its presence is unambiguous.
    if any(os.path.exists(p) for p in ("/ostree", "/sysroot/ostree")) \
            and shutil.which("rpm-ostree"):
        cands.append(["rpm-ostree", "initramfs", "--enable", "--arg=--force"])

    # Debian family — definitive when present.
    if shutil.which("update-initramfs"):
        cands.append(["update-initramfs", "-u", "-k", "all"])

    # Limine mkinitcpio hook (CachyOS): rebuilds every kernel, no presets needed.
    if shutil.which("limine-mkinitcpio"):
        cands.append(["limine-mkinitcpio"])

    # Standard mkinitcpio — only with presets, else `-P` errors out.
    if shutil.which("mkinitcpio") and glob.glob("/etc/mkinitcpio.d/*.preset"):
        cands.append(["mkinitcpio", "-P"])

    # dracut — Fedora/RHEL/SUSE and Arch-with-dracut.
    if shutil.which("dracut"):
        cands.append(["dracut", "--force", "--regenerate-all"])

    # booster (Arch alternative): regenerate all known kernels.
    if shutil.which("booster"):
        cands.append(["booster", "build"])

    # systemd UKI: reinstall-kernels (mkinitcpio's UKI helper) or kernel-install.
    if shutil.which("reinstall-kernels"):
        cands.append(["reinstall-kernels"])

    return cands


def _rebuild_initramfs():
    """Rebuild the initramfs so the module blacklist applies at next boot.

    Tries each applicable generator in turn (see _initramfs_candidates) until one
    succeeds. Returns True on the first success. If every candidate fails — or
    none is applicable — returns False and forwards the real error to stderr so
    the Vantage helper can surface it (instead of a bare "exited 1").
    """
    cands = _initramfs_candidates()
    if not cands:
        log.warning("no known initramfs tool found; skipping rebuild")
        sys.stderr.write("vantage: no supported initramfs generator found; "
                         "rebuild the initramfs manually before rebooting\n")
        return False

    inhibit = ["systemd-inhibit", "--who=vantage",
               "--why=Rebuilding initramfs", "--"] if shutil.which("systemd-inhibit") else []
    last_err = "no output"
    for cmd in cands:
        try:
            p = subprocess.run(inhibit + cmd, stdout=subprocess.DEVNULL,
                               stderr=subprocess.PIPE, text=True, check=False)
        except OSError as exc:
            last_err = "could not run %s: %s" % (cmd[0], exc)
            log.warning(last_err)
            continue
        if p.returncode == 0:
            log.info("initramfs rebuilt with %s", cmd[0])
            return True
        err = (p.stderr or "").strip().splitlines()
        last_err = "%s failed (rc=%s): %s" % (
            cmd[0], p.returncode, err[-1] if err else "no output")
        log.warning("initramfs rebuild: %s", last_err)

    sys.stderr.write("vantage: initramfs rebuild failed — %s\n" % last_err)
    return False


def set_mode(mode):
    """Switch graphics mode (root only). Returns True on success.

    A reboot is required for the change to take effect.
    """
    if mode not in MODES:
        log.error("unknown gpu mode %r", mode)
        return False

    # Stamp the persistent dGPU marker (we only get here because the machine has
    # one). Best-effort: failure to write it must not abort the switch.
    try:
        _write(MARKER_PATH, "1\n")
    except OSError:
        log.warning("could not write dGPU marker %s", MARKER_PATH)

    if mode == "integrated":
        _persistenced("disable")
        _write(BLACKLIST_PATH, BLACKLIST_CONTENT)
        _write(UDEV_INTEGRATED_PATH, UDEV_INTEGRATED_CONTENT)
    else:  # hybrid — revert to distro default
        _remove_owned()
        _persistenced("enable")

    return _rebuild_initramfs()
